### ISSUE TITLE
config.js lines are very long

### ISSUE THREAD

**Issue by equaeghe** [equaeghe/infcloud#1]
The lines in the configuration file `config.js` are very long. This hampers readability.
Suggested modification: split up lines, add white space, and use more block comments.

**Comment by equaeghe** [comment]
I've made a proposal: see config.js resulting from commit dc62aa8dbc58d752d5b3a63ae5641e8ac14eac94.

**Comment by jgehrcke** [comment]
I love to see infcloud on GitHub. But could you please clarify the relation between this project here and the original upstream project? Do you plan to develop your own fork, indepedently, or do you have an agreement with the original developers in the following sense: are the changes proposed here likely to be merged into upstream? Do the original developers look at the issues reported here?

Especially, I am wondering whether it makes sense to invest into *this* repository here (by submitting issues or even pull requests) of it that could be a waste of time.

I think you know what I mean :-)

**Comment by equaeghe** [comment]
It is impolite to hijack this issue for an unrelated question. Please ask your question again in a new issue. Afterwards, I will remove the unrelated comments you generated in this issue.

**Comment by equaeghe** [comment]
Fixed in 0.13.0.
