### ISSUE TITLE
sabredav: event autosync not working - REPORT request not supported - error 415

### ISSUE THREAD

**Issue by minami-o** [equaeghe/infcloud#25]
Hi there,
Since version [2.1.0alpha1](https://github.com/fruux/sabre-dav/blob/master/CHANGELOG.md#210-alpha1-2014-09-23), sabredav replies to an unsupported REPORT request with error code 415 instead of 403.
This error code is currently not handled in the [webdav_protocol.js](https://github.com/equaeghe/infcloud/blob/master/webdav_protocol.js#L3051) file, although the REPORT request sent by infcloud when it tries to synchronize events is not supported by sabredav, which results in an error being thrown out, related to CalDAVnetLoadCollection.
You can see a little hazard sign next to all available calendar when the sync fails.
To solve this, all you need is to add the 415 code in the list of handled exceptions on the very line mentioned above:
before:

>  if((objAJAXRequest.status==400 /\* bad request */ || objAJAXRequest.status==403 /\* forbidden (for stupid servers) */ || objAJAXRequest.status==501 /\* unimplemented */) && inputCollection.forceSyncPROPFIND!=true /\* prevent recursion */)

after:

>  if((objAJAXRequest.status==400 /\* bad request */ || objAJAXRequest.status==403 /\* forbidden (for stupid servers) */ || objAJAXRequest.status==415 /\* sabredav: REPORT request not supported */ || objAJAXRequest.status==501 /\* unimplemented */) && inputCollection.forceSyncPROPFIND!=true /\* prevent recursion */)

The CalDAVnetLoadCollection then automatically uses a PROPFIND request as a replacement for the REPORT one, which settles the issue.

If I have time, I'll create pull requests for this and the other issue I opened earlier today.

**Comment by equaeghe** [comment]
This is a personal fork of infcloud. Please contact the developers directly: https://www.inf-it.com/open-source/clients/infcloud/
