### ISSUE TITLE
Clarification for the relation between this fork and the original upstream project

### ISSUE THREAD

**Issue by jgehrcke** [equaeghe/infcloud#26]
First of all, thanks for your work on infcloud and please excuse my earlier issue "hijacking". If you feel that the following question deserves its own issue then it should have it.

So, I love to see infcloud on GitHub. But could you please clarify, maybe in the README, the relation between this project here and the original upstream project? This could motivate contributions to _this_ repository here. Do you plan to develop your own fork, indepedently, or do you have an agreement with the original developers in the following sense: are the changes proposed here likely to be merged into upstream? Do the original developers look at the issues reported here?

Especially, I am wondering whether it makes sense to invest into _this_ repository by submitting issues or even pull requests when I eventually would like to influence the upstream project, or if that does not seem likely.

Thanks for clarification!

**Comment by equaeghe** [comment]
This is a personal fork for minor tweaks. It is not intended for parallel development. The infcloud developers do not merge material from here. So: it does not make sense to invest in this repo. It is public because some may have a use for my minor tweaks.

**Comment by jgehrcke** [comment]
Thanks for sharing your private tweaks, then :-)!

I have sent an email to the original authors and asked them if they consider putting infcloud on GitHub. From my point of view, the issues you have opened up here really could go into an official tracker.
